name: Continuous Integration and Deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint

    - name: Run Prettier Check
      run: npx prettier --check .

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build
